name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - '*'

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.2'
          cache: true
      # More assembly might be required: Docker logins, GPG, etc. It all depends
      # on your needs.
      - uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN}}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro'
          # distribution:
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      - run: echo "VERSION_NAME=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
      - run: echo $VERSION_NAME
      - uses: actions/upload-artifact@v2
        with:
          name: goreleaser-deb
          path: dist/perfops_${{ env.VERSION_NAME }}_linux_amd64.deb
      - uses: actions/upload-artifact@v2
        with:
          name: goreleaser-rpm
          path: dist/perfops_${{ env.VERSION_NAME }}_linux_amd64.rpm

  deploy:
    needs: goreleaser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: goreleaser-deb
      - uses: actions/download-artifact@v2
        with:
          name: goreleaser-rpm
      - run: echo "VERSION_NAME=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
      - run: echo perfops-cli_${{ env.VERSION_NAME }}_linux_amd64.deb
      - run: ls -la
      - uses: ProspectOne/upload-packagecloud@v1
        with:
          DEB-PACKAGE-NAME: perfops_${{ env.VERSION_NAME }}_linux_amd64.deb
          RPM-PACKAGE-NAME: perfops_${{ env.VERSION_NAME }}_linux_amd64.rpm
          PACKAGECLOUD-USERNAME: p1
          PACKAGECLOUD-REPO: perfops
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}