name: Release

on: [push, pull_request]

jobs:
  test-package:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    runs-on: ubuntu-latest
    name: test-package
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Go 1.11 and Test
        uses: cedrickring/golang-action/go1.11@1.6.0
        env:
          IMPORT: "ProspectOne/perfops-cli"

  publish-package:
    needs: test-package
    name: publish-package
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
     - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*' 
      - uses: actions/checkout@v1
      - name: install
        run: |
          npm install semantic-release @semantic-release/exec -g
      - name: release
        run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
